INSERT INTO productos(nombreProducto, imagenProductoRuta, marcaProducto, precioProducto, cantidadProducto, descripcionProducto, categoriaProducto) 
	VALUES('Tarjeta de Video Sapphire AMD Radeon RX 9070 XT', '/img/sapphireRadeonRx9070xt16gb.png', 'AMD', 14389.00, 5, 'Componente de alto rendimiento diseñado para satisfacer las necesidades de los entusiastas de los videojuegos y los profesionales del diseño gráfico.', 'Tarjeta gráfica');
INSERT INTO productos(nombreProducto, imagenProductoRuta, marcaProducto, precioProducto, cantidadProducto, descripcionProducto, categoriaProducto) 
	VALUES('Tarjeta de Video MSI NVIDIA GeForce RTX 5080 VANGUARD SOC', '/img/geForceRTX508016GVanguard.png', 'Nvidia', 28549.00, 2, 'Esta tarjeta pertenece a la familia de procesadores gráficos NVIDIA y está diseñada para ofrecer una experiencia visual excepcional, soportando hasta cuatro pantallas simultáneamente.', 'Tarjeta gráfica');
INSERT INTO productos(nombreProducto, imagenProductoRuta, marcaProducto, precioProducto, cantidadProducto, descripcionProducto, categoriaProducto) 
	VALUES('Procesador Intel Core Ultra 5 245K con Intel Graphics', '/img/intelCoreULTRA5245K.jpg', 'Intel', 4579.00, 12, 'Este procesador cuenta con 14 núcleos, de los cuales 6 son núcleos de rendimiento y 8 son núcleos eficientes, ofreciendo un rendimiento total de hasta 30 TOPs.', 'Procesador');
INSERT INTO productos(nombreProducto, imagenProductoRuta, marcaProducto, precioProducto, cantidadProducto, descripcionProducto, categoriaProducto) 
	VALUES('Procesador AMD Ryzen 7 9800X3D con AMD Radeon Graphics', '/img/amdRyzen78900X3DAM5.jpg', 'AMD', 9479.00, 7, ' Es una potente unidad de procesamiento diseñada para el segmento de escritorio. Con una litografía de 4 nm, este procesador de la familia AMD Ryzen 7 pertenece a la generación 9000.', 'Procesador');
INSERT INTO productos(nombreProducto, imagenProductoRuta, marcaProducto, precioProducto, cantidadProducto, descripcionProducto, categoriaProducto) 
	VALUES('Memoria RAM XPG Spectrix D35G DDR4, 3200MHz, 16GB, CL16, XMP', '/img/memoriaGAMMIXD35DDR4.png', 'XPG', 919.00, 34, 'Ha sido sometido a estrictos procedimientos de selección y control, superando pruebas de fiabilidad y compatibilidad, y ofrece un producto resistente y duradero que representa la más alta calidad.', 'RAM');
INSERT INTO productos(nombreProducto, imagenProductoRuta, marcaProducto, precioProducto, cantidadProducto, descripcionProducto, categoriaProducto) 
	VALUES('Kit Memoria RAM Kingston FURY Beast DDR4, 3200MHz, 16GB - 2 x 8GB, CL16, XMP', '/img/memoriaKingstonFury16GB.png', 'Kingston', 1309.00, 28, 'Este módulo de memoria interna tipo DDR4 presenta un color negro y cuenta con un factor de forma de 288 pines DIMM.', 'RAM');
INSERT INTO productos(nombreProducto, imagenProductoRuta, marcaProducto, precioProducto, cantidadProducto, descripcionProducto, categoriaProducto) 
	VALUES('SSD Adata Legend 900 Pro NVMe, 2 TB, M.2, 6500 MB/s Escritura, 7400 MB/s Lectura, PCI Express 4.0', '/img/ssdAdataLegend900Pro2TB.png', 'Adata', 2279.00, 67, 'Es una unidad de almacenamiento de alto rendimiento diseñada para satisfacer las necesidades de usuarios exigentes. Con una capacidad de 2TB, este dispositivo ofrece una velocidad de lectura de hasta 7400 MB/s y una velocidad de escritura de 6500 MB/s.', 'SSD');
INSERT INTO productos(nombreProducto, imagenProductoRuta, marcaProducto, precioProducto, cantidadProducto, descripcionProducto, categoriaProducto) 
	VALUES('SSD Samsung 9100 PRO NVMe, 1TB, M.2, 13000 MB/s Escritura, 14700 MB/s Lectura, PCI Express 5.0', '/img/ssdSamsung9100Pro1TB.jpg', 'Samsung', 4339.00, 32, 'Es una unidad de almacenamiento de alto rendimiento diseñada para PC y computadoras portátiles. Con un factor de forma M.2 de 2280 (22 x 80 mm), este dispositivo ofrece una capacidad de 1 TB, ideal para almacenar grandes volúmenes de datos.', 'SSD');
INSERT INTO productos(nombreProducto, imagenProductoRuta, marcaProducto, precioProducto, cantidadProducto, descripcionProducto, categoriaProducto) 
	VALUES('Tarjeta Madre MSI A520M-A PRO, Micro-ATX, Socket AM4, AMD A520, 64GB DDR4, HDMI para AMD', '/img/msiA520MAProMotherboard.png', 'Msi', 1309.00, 13, 'es un componente esencial para la construcción de PC, diseñada para procesadores AMD con socket AM4. Esta placa base cuenta con un factor de forma Micro ATX, lo que la hace adecuada para una variedad de gabinetes.', 'Tarjeta madre');
INSERT INTO productos(nombreProducto, imagenProductoRuta, marcaProducto, precioProducto, cantidadProducto, descripcionProducto, categoriaProducto) 
	VALUES('Gabinete InWin InWin F5, Full Tower, ATX/EATX/Micro-ATX/Mini-ITX, USB 3.0, sin Fuente, 3 Ventiladores Instalados, Blanco', '/img/inWinF5FullTowerATX.jpg', 'InWind', 2009.00, 4, 'es una opción destacada para quienes buscan un chasis espacioso y funcional. Este gabinete permite la instalación de hasta tres ventiladores en la parte inferior y cuenta con capacidad para radiadores de hasta 240 y 280 mm.', 'Gabinete');
INSERT INTO productos(nombreProducto, imagenProductoRuta, marcaProducto, precioProducto, cantidadProducto, descripcionProducto, categoriaProducto) 
	VALUES('Gabinete NZXT H3 Flow, Midi-Tower, Micro-ATX/Mini-ITX, USB 3.0, sin Fuente, 1 Ventilador Instalado, Negro', '/img/nzxtH31MidiTower.png', 'NZXT', 1329.00, 6, 'El Gabinete NZXT H31 es un modelo de tipo Midi-Tower diseñado para placas madre Micro ATX y Mini-ITX. Su estructura presenta un acabado en color negro y está fabricado con materiales como red, SGCC y vidrio templado, lo que le otorga un aspecto moderno y elegante.', 'Gabinete');
INSERT INTO productos(nombreProducto, imagenProductoRuta, marcaProducto, precioProducto, cantidadProducto, descripcionProducto, categoriaProducto) 
	VALUES('Gabinete Hyte Y70, Midi-Tower, ATX/EATX/Micro-ATX/Mini-ITX, USB 3.0, sin Fuente, sin Ventiladores Instalados, Blanco', '/img/hyteY70MidiTowerATX.jpg', 'HYTE', 4169.00, 2, 'El Gabinete Hyte Y70 es un modelo de torre media diseñado para sistemas de PC, compatible con formatos de placa madre ATX, EATX, ITX y Micro ATX. Su estructura presenta un panel de vidrio templado que permite una visualización clara del interior.', 'Gabinete');
INSERT INTO productos(nombreProducto, imagenProductoRuta, marcaProducto, precioProducto, cantidadProducto, descripcionProducto, categoriaProducto) 
	VALUES('Fuente de Poder Gigabyte UD750GM 80 PLUS Gold, Modular, 24-pin ATX, 120mm, 750W', '/img/gigaByteUltraDurableUD750GM.png', 'Gigabyte', 1819.00, 9, 'Es una unidad de alimentación diseñada para ofrecer un rendimiento eficiente y confiable. Con una potencia nominal de 750 W y una potencia combinada de 732 W en el riel de +12 V, esta fuente proporciona la energía necesaria para sistemas de alto rendimiento.', 'Fuente de alimentación');
INSERT INTO productos(nombreProducto, imagenProductoRuta, marcaProducto, precioProducto, cantidadProducto, descripcionProducto, categoriaProducto) 
	VALUES('Fuente de Poder Corsair RM850e 80 PLUS Gold, Modular, 24-pin ATX, 120mm, 850W', '/img/corsair850W80PlusGoldModular.png', 'Corsair', 1989.00, 6, 'Ofrece una potencia nominal de 850W, ideal para sistemas que requieren un suministro de energía confiable y eficiente. Su diseño modular permite una gestión óptima de los cables, facilitando la instalación y mejorando el flujo de aire dentro del chasis.', 'Fuente de alimentación');
INSERT INTO productos(nombreProducto, imagenProductoRuta, marcaProducto, precioProducto, cantidadProducto, descripcionProducto, categoriaProducto) 
	VALUES('Ventilador Cooler Master MasterFan MF120 S3, 120mm, 1800RPM, ARGB, Negro', '/img/coolerMaster120mmMasterFanMF120.jpg', 'Cooler Master', 164.00, 112, 'Iluminación ARGB de triple bucle 1800 RPM, 52 CFM Rodamiento de rifle Diseño de ventilador con balance de aire Almohadillas antivibración RM 49.', 'Refrigeracion');
INSERT INTO productos(nombreProducto, imagenProductoRuta, marcaProducto, precioProducto, cantidadProducto, descripcionProducto, categoriaProducto) 
	VALUES('Ventilador XPG Hurricane 140mm ARGB PWM, 140mm, 1800RPM, ARGB, Negro/Blanco', '/img/xpgFanCoolerAdataVento140.png', 'XPG', 277.00, 64, 'El ventilador XPG HURRICANE 140 ARGB PWM ofrece algo más que impresionantes efectos de luces de doble anillo. La velocidad del ventilador alcanza las 2,000 RPM, generando hasta 61.5 CFM de aire frío con 1.42 mmAq de presión estática.', 'Refrigeracion');
INSERT INTO productos(nombreProducto, imagenProductoRuta, marcaProducto, precioProducto, cantidadProducto, descripcionProducto, categoriaProducto) 
	VALUES('Ventilador XPG VENTO, 120mm, 1200RPM, Negro', '/img/xpgFanCoolerAdataVento120.png', 'XPG', 147.00, 75, 'El ventilador VENTO 120 agota el calor con un flujo de aire de 45,3 CFM a solo 23 dBA de nivel de ruido, mientras que el VENTO 120 ARGB agrega más efectos de iluminació.', 'Refrigeracion');
INSERT INTO productos(nombreProducto, imagenProductoRuta, marcaProducto, precioProducto, cantidadProducto, descripcionProducto, categoriaProducto) 
	VALUES('Tarjeta Madre ASUS Prime B760M-A-CSM, Micro-ATX, LGA 1700, Intel B760, 128GB DDR5, HDMI/DP para Intel', '/img/asusPrimeB760MAATX.png', 'Asus', 1689.00, 12, 'Es un componente esencial para la construcción de un PC de alto rendimiento. Diseñada en un factor de forma Micro ATX, esta tarjeta madre es compatible con procesadores Intel en el socket LGA 1700, incluyendo las familias Intel® Celeron®, Intel® Pentium® Gold, Intel® Core™ i3, i5, i7 e i9.', 'Tarjeta madre');
INSERT INTO productos(nombreProducto, imagenProductoRuta, marcaProducto, precioProducto, cantidadProducto, descripcionProducto, categoriaProducto) 
	VALUES('Tarjeta Madre MSI MAG X870 TOMAHAWK WIFI, ATX, Socket AM5, AMD X870, 256GB DDR5, HDMI/DP para AMD', '/img/magX870TomahawkWifi.png', 'Msi', 5859.00, 15, 'Está diseñada para ofrecer un rendimiento excepcional en sistemas de PC. Con un factor de forma ATX, esta placa es compatible con el socket AM5 y soporta procesadores AMD Ryzen™ 7.', 'Tarjeta madre');
INSERT INTO productos(nombreProducto, imagenProductoRuta, marcaProducto, precioProducto, cantidadProducto, descripcionProducto, categoriaProducto) 
	VALUES('Tarjeta de Video MSI NVIDIA GeForce RTX 5060 Ti SHADOW 2X OC PLUS, 16GB 128-bit GDDR7, PCI Express 5.0', '/img/msiGeForceRTX5060Ti16GB.png', 'Msi', 10209.00, 8, 'Pertenece a la línea GeForce y está diseñada para ofrecer un rendimiento gráfico excepcional. Esta tarjeta cuenta con un procesador gráfico GeForce RTX 5060 Ti, que forma parte de la serie de GPU GeForce RTX 50.', 'Tarjeta gráfica');
INSERT INTO productos(nombreProducto, imagenProductoRuta, marcaProducto, precioProducto, cantidadProducto, descripcionProducto, categoriaProducto) 
	VALUES('Tarjeta de Video ASUS AMD Radeon RX 9070 XT Prime OC, 16GB 256-bit GDDR6, PCI Express x16 5.0', '/img/asusAmdRadeonRx907016Gb.png', 'Asus', 13889.00, 9, 'Pertenece a la línea Radeon RX y está equipada con un procesador gráfico Radeon RX 9070 XT. Esta tarjeta cuenta con una memoria de adaptador gráfico de 16GB, utilizando el tipo de memoria GDDR6.', 'Tarjeta gráfica');
INSERT INTO productos(nombreProducto, imagenProductoRuta, marcaProducto, precioProducto, cantidadProducto, descripcionProducto, categoriaProducto) 
	VALUES('Tarjeta de Video Gigabyte AMD Radeon RX 7600 GAMING OC, 8GB 128-bit GDDR6, PCI Express 4.0', '/img/gigaByteAmdRadeonRx76008Gb.png', 'Gigabyte', 5809.00, 11, 'Es un componente de alto rendimiento diseñado para satisfacer las necesidades de los entusiastas de los videojuegos y los profesionales del diseño gráfico. Esta tarjeta cuenta con un procesador gráfico Radeon RX 7600.', 'Tarjeta gráfica');
INSERT INTO productos(nombreProducto, imagenProductoRuta, marcaProducto, precioProducto, cantidadProducto, descripcionProducto, categoriaProducto) 
	VALUES('Tarjeta de Video ASUS NVIDIA GeForce RTX 5070 TUF Gaming OC Edition, 12GB 192-bit GDDR7, PCI Express 5.0', '/img/asusNvidiaGeForceRTX507012Gb.png', 'Asus', 14929.00, 6, 'Componente de alto rendimiento diseñado para entusiastas de los videojuegos y profesionales del diseño gráfico. Presenta un color multicolor y utiliza la interfaz PCI Express 5.0.', 'Tarjeta gráfica');
INSERT INTO productos(nombreProducto, imagenProductoRuta, marcaProducto, precioProducto, cantidadProducto, descripcionProducto, categoriaProducto) 
	VALUES('Kit Memoria RAM XPG GAMMIX D35 DDR4, 3200MHz, 16GB - 2 x 8GB, CL16, XMP', '/img/xpgGammixDDR416Gb.jpg', 'XPG', 1089.00, 34, 'Componente para: PC, Memoria interna: 16 GB, Diseño de memoria (módulos x tamaño): 2 x 8 GB, Tipo de memoria interna: DDR4, Velocidad de memoria del reloj: 3200 MHz', 'RAM');
INSERT INTO productos(nombreProducto, imagenProductoRuta, marcaProducto, precioProducto, cantidadProducto, descripcionProducto, categoriaProducto) 
	VALUES('Memoria RAM Patriot Viper Steel DDR4, 3200MHz, 8GB, CL16, XMP, Gris', '/img/patriotViperSteelDDR48GB.jpg', 'Patriot', 474.00, 22, 'Es un componente para PC/servidor con un diseño de memoria de 1 x 8GB. Tiene un factor de forma de 288-pin DIMM y un tipo de memoria interna DDR4. Con una velocidad de memoria del reloj de 3200MHz y una latencia CAS de 16', 'RAM');
INSERT INTO productos(nombreProducto, imagenProductoRuta, marcaProducto, precioProducto, cantidadProducto, descripcionProducto, categoriaProducto) 
	VALUES('Memoria RAM Team Group DELTA RGB DDR4, 3200MHz, 8GB, CL16', '/img/teamGroupDeltRgbDDR48Gb.jpg', 'Team Group', 479.00, 34, 'Es plug and play. La sobreaceleración puede ser muy sencilla sin la molestia de ajustar manualmente el BIOS. Es compatible con las plataformas Intel y AMD, por lo que los gamers pueden disfrutar de la sobreaceleración fácilmente y sin preocupaciones.', 'RAM');
INSERT INTO productos(nombreProducto, imagenProductoRuta, marcaProducto, precioProducto, cantidadProducto, descripcionProducto, categoriaProducto) 
	VALUES('Memoria RAM Adata Premier DDR4, 2666MHz, 8GB, CL19, Verde', '/img/adataPremierDDR48Gb.png', 'Adata', 433.00, 23, 'Con una velocidad de 2666MHz y una capacidad de 8GB, modelo AD4U26668G19-SGN, es un componente esencial para el rendimiento de PC y servidores. Esta memoria opera a un voltaje de 1.2 V y presenta una configuración de módulos de 1024M x 16. La latencia CAS es de 19.', 'RAM');
INSERT INTO productos(nombreProducto, imagenProductoRuta, marcaProducto, precioProducto, cantidadProducto, descripcionProducto, categoriaProducto) 
	VALUES('Memoria RAM Kingston FURY Beast Black DDR4, 3200MHz, 16GB, CL16, XMP', '/img/kingstonFuryBeastDDR416Gb.png', 'Kingston', 1089.00, 12, 'Es un componente para PC/servidor con una capacidad de 16 GB y una velocidad de memoria del reloj de 3200MHz. Presenta un diseño de memoria de 1 módulo de 16GB en formato 288-pin DIMM.', 'RAM');
INSERT INTO productos(nombreProducto, imagenProductoRuta, marcaProducto, precioProducto, cantidadProducto, descripcionProducto, categoriaProducto) 
	VALUES('Disco Duro Interno HGST HUS726T6TALE6L4 3.5", 6TB, SATA III, 6 Gbit/s, 7200RPM, 256MB Caché', '/img/hgstHDD6Tb7200Rpm.jpg', 'HGST', 4079.00, 22, 'Es una unidad de disco duro con una altura de 26,1 mm y una capacidad de 6000 GB. Opera con un voltaje de 5 / 12 V y tiene un consumo energético de 7 W en funcionamiento y 5,9 W en espera.', 'HDD');
INSERT INTO productos(nombreProducto, imagenProductoRuta, marcaProducto, precioProducto, cantidadProducto, descripcionProducto, categoriaProducto) 
	VALUES('Disco Duro Interno Toshiba X300 3.5", 10TB, SATA III, 6 Gbit/s, 7200RPM, 512MB Caché', '/img/toshibaHDDX30010Tb7200Rpm.jpg', 'Toshiba', 4599.00, 4, 'Es una unidad de disco duro de 3.5" que ofrece un rendimiento óptimo para sistemas de PC. Con una interfaz SATA III, permite una velocidad de transferencia de datos de hasta 6 Gbit/s.', 'HDD');
INSERT INTO productos(nombreProducto, imagenProductoRuta, marcaProducto, precioProducto, cantidadProducto, descripcionProducto, categoriaProducto) 
	VALUES('Disco Duro Interno Western Digital WD2003FZEX 3.5", 2TB, SATA III, 6 Gbit/s, 7200RPM, 64MB Caché', '/img/westernDigital2003FZEX2Tb7200Rpm.jpg', 'Western digital', 2519.00, 9, 'Cuenta con una interfaz Serial ATA III y un voltaje de operación de 5 /12 V. La velocidad de transferencia en la interfaz del disco duro es de 6 Gbit/s y su tamaño es de 3.5', 'HDD');
INSERT INTO productos(nombreProducto, imagenProductoRuta, marcaProducto, precioProducto, cantidadProducto, descripcionProducto, categoriaProducto) 
	VALUES('Disco Duro Interno Seagate Barracuda 3.5", 6TB, SATA III, 6 Gbit/s, 5400RPM, 256MB Caché', '/img/seagateBarracudaHDD6Tb5400Rpm.jpg', 'Seagate', 2999.00, 7, 'Es un componente de almacenamiento diseñado para su uso en servidores y estaciones de trabajo. Con una capacidad de almacenamiento masivo de hasta 6 terabytes.', 'HDD');
INSERT INTO productos(nombreProducto, imagenProductoRuta, marcaProducto, precioProducto, cantidadProducto, descripcionProducto, categoriaProducto) 
	VALUES('Disco Duro Interno Toshiba L200 2.5", 2TB, SATA III, 6 Gbit/s, 5400RPM, 128MB Caché', '/img/toshibaHDDL2002Tb5400Rpm.jpg', 'Toshiba', 1359.00, 9, 'Con una capacidad de 2TB y una interfaz Serial ATA III ofrece una velocidad de transferencia de datos de 6 Gbit/s. Con un peso de 92 g y dimensiones de 69.8 mm de ancho, 100 mm de altura y 9.5 mm de profundidad.', 'HDD');
INSERT INTO productos(nombreProducto, imagenProductoRuta, marcaProducto, precioProducto, cantidadProducto, descripcionProducto, categoriaProducto) 
	VALUES('Procesador AMD Ryzen 9 9950X3D con AMD Radeon Graphics, Socket AM5, 5.7GHz, 16 Núcleos, 144MB Caché', '/img/amdRyzen99950x3d.jpg', 'AMD', 12979.00, 3, 'Se destaca por su alto rendimiento y eficiencia. Con una frecuencia base de 4.3 GHz y una frecuencia turbo que alcanza hasta 5.7 GHz, este procesador está diseñado para satisfacer las demandas de los usuarios más exigentes.', 'Procesador');
INSERT INTO productos(nombreProducto, imagenProductoRuta, marcaProducto, precioProducto, cantidadProducto, descripcionProducto, categoriaProducto) 
	VALUES('Procesador AMD Ryzen 9 7950X con AMD Radeon Graphics, Socket AM5, 5.7GHz, 16 Núcleos, 64MB Caché', '/img/amdRyzen97950X.jpg', 'AMD', 7449.00, 6, 'Con una frecuencia base de 4.5 GHz y una frecuencia turbo que alcanza hasta 5.7 GHz, este procesador ofrece un rendimiento excepcional. Dispone de 16 núcleos y 32 filamentos.', 'Procesador');
INSERT INTO productos(nombreProducto, imagenProductoRuta, marcaProducto, precioProducto, cantidadProducto, descripcionProducto, categoriaProducto) 
	VALUES('Procesador Intel Core i5-12600KF, LGA 1700, 4.90GHz, 10 Núcleos, 20MB Caché, No incluye Disipador - 12va.', '/img/intelCorei512600kf.jpg', 'Intel', 3059.00, 7, 'Pertenece a la 12ª generación de procesadores Intel y utiliza el socket LGA 1700. Este modelo cuenta con una frecuencia base de 3.7 GHz y puede alcanzar hasta 4.9 GHz en modo turbo.', 'Procesador');
INSERT INTO productos(nombreProducto, imagenProductoRuta, marcaProducto, precioProducto, cantidadProducto, descripcionProducto, categoriaProducto) 
	VALUES('Procesador AMD Ryzen 5 8400F, Socket AM5, 4.70GHz, 6 Núcleos, 16MB Caché', '/img/amdRyzen58400F.jpg', 'AMD', 2759.00, 16, 'Pertenece a la generación 8000 de AMD y está diseñado para el segmento de mercado de escritorio. Este modelo cuenta con 6 núcleos y 12 hilos, lo que permite un rendimiento eficiente en tareas multitarea y aplicaciones exigentes.', 'Procesador');